export const GUN_STATS = {
  GUN_BASIC: {
    key: 'GUN_BASIC',
    damage: 1,
    range: 20,
    bulletSpeed: 70,
    fireRate: 1500,
    accuracy: 0,
    scale: 1,
    pierce: 1,
    tint: 0xff0000,
  },
  GUN_SLOW: {
    key: 'GUN_SLOW',
    damage: 1,
    range: 20,
    fireRate: 1500,
    slow: true,
    bulletSpeed: 100,
    accuracy: 0,
    pierce: 1,
    scale: 2,
    tint: 0x0000ff,
  },
}
